# config.yaml

# TCP Server Connection Settings
tcp:
  host: "192.168.10.137"
  port: 5000

# Evaluation Parameters
evaluation:
  rate_hz: 200.0 # Processor thread reporting rate in Hz

# Ground Truth Coordinates
ground_truth:
  latitude: null
  longitude: null

# Logging Configuration
logging:
  enable: true # Enable logging of report data lines
  file_path: null # Path to log file. If null and enable is true, a default is generated.
                  # Example: ".gnss_log/gnss_eval_from_config.log"
